# Site settings
title: Maryana e Bruno!
email: bhbarbosa@gmail.com
url: https://brunoemarycombr.github.io
description: "O site do nosso casamento!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#F9EACC'
  # primary-dark: '#F4E2BE'
  links: '#62892A'

# Footer settings
footer: Maryana & Bruno

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#   - title: facebook
#     url: https://facebook.com

page-sections:
    - name: sobre
      menu: true
      title: Sobre nós
    - name: galeria
      menu: true
      title: Galeria
    - name: pais
      menu: true
      title: Aos pais
    - name: padrinhos
      menu: true
      title: Aos padrinhos
    - name: familiares
      menu: true
      title: Aos familiares
    - name: quantofalta
      menu: true
      title: Quanto falta?
    - name: cerimoniaerecepcao
      menu: true
      title: Cerimônia e Recepção
    - name: listadepresentes
      menu: true
      title: Lista de Presentes
#    - name: map
#      menu: false
#      title: Local
   
# Build settings
markdown: kramdown
permalink: pretty
